"""Minimal Python SDK surface for AANA workflow checks."""

import json
import pathlib

from eval_pipeline.agent_api import (
    WORKFLOW_CONTRACT_VERSION,
    append_audit_record,
    apply_shadow_mode,
    audit_aix_drift_report,
    audit_aix_drift_report_file,
    audit_dashboard,
    audit_dashboard_file,
    audit_event_check,
    audit_redaction_report,
    audit_workflow_batch,
    audit_workflow_check,
    check_workflow,
    check_workflow_batch,
    check_workflow_request,
    evidence_connector_marketplace,
    evidence_connector_contracts,
    evidence_integration_coverage,
    evidence_integration_stubs,
    evidence_mock_connector_matrix,
    export_audit_metrics,
    export_audit_metrics_file,
    load_audit_records,
    load_evidence_mock_fixtures,
    load_evidence_registry,
    normalize_evidence_object,
    run_evidence_mock_connector,
    schema_catalog,
    support_evidence_boundary,
    summarize_audit_file,
    summarize_audit_records,
    validate_audit_file,
    validate_audit_metrics_export,
    validate_audit_records,
    validate_workflow_batch_evidence,
    validate_workflow_batch_request,
    validate_evidence_registry,
    validate_workflow_evidence,
    validate_workflow_request,
    write_audit_reviewer_report,
)
from eval_pipeline.aix import calculate_aix, decision_from_score
from eval_pipeline.aix_audit import (
    AIX_REPORT_SCHEMA,
    build_aix_report,
    build_enterprise_dashboard,
    load_enterprise_adapter_config,
    load_enterprise_calibration_fixtures,
    materialize_enterprise_ops_batch,
    render_aix_report_markdown,
    run_enterprise_ops_aix_audit,
    validate_enterprise_adapter_config,
    validate_enterprise_calibration_fixtures,
    validate_aix_report,
)
from eval_pipeline.enterprise_connector_readiness import (
    DEFAULT_ENTERPRISE_CONNECTOR_READINESS_PATH,
    ENTERPRISE_CONNECTOR_READINESS_TYPE,
    ENTERPRISE_CONNECTOR_READINESS_VERSION,
    REQUIRED_CONNECTOR_IDS,
    default_enterprise_connectors,
    enterprise_connector_readiness_plan,
    validate_enterprise_connector_readiness_plan,
    write_enterprise_connector_readiness_plan,
)
from eval_pipeline.durable_audit_storage import (
    DEFAULT_DURABLE_AUDIT_CONFIG_PATH,
    DEFAULT_DURABLE_AUDIT_DIR,
    DEFAULT_DURABLE_AUDIT_JSONL,
    DEFAULT_DURABLE_AUDIT_MANIFEST,
    DURABLE_AUDIT_STORAGE_TYPE,
    DURABLE_AUDIT_STORAGE_VERSION,
    LocalDurableAuditStorage,
    append_durable_audit_records,
    durable_audit_storage_config,
    import_audit_log_to_durable_storage,
    validate_durable_audit_storage_config,
    verify_durable_audit_storage,
    write_durable_audit_storage_config,
)
from eval_pipeline.enterprise_live_connectors import (
    DEFAULT_ENTERPRISE_LIVE_CONNECTORS_PATH,
    ENTERPRISE_LIVE_CONNECTORS_TYPE,
    ENTERPRISE_LIVE_CONNECTORS_VERSION,
    EXECUTION_MODES as ENTERPRISE_CONNECTOR_EXECUTION_MODES,
    SUPPORT_ACTION_CONNECTOR_IDS,
    EnterpriseConnectorError,
    EnterpriseConnectorManifest,
    EnterpriseHTTPJSONConnector,
    aana_allows_execution,
    build_enterprise_support_connectors,
    default_enterprise_live_connector_config,
    enterprise_connector_manifests,
    load_enterprise_live_connector_config,
    run_enterprise_support_connector_smoke,
    validate_enterprise_live_connector_config,
    write_enterprise_live_connector_config,
)
from eval_pipeline.enterprise_support_demo import (
    ENTERPRISE_SUPPORT_DEMO_VERSION,
    build_enterprise_support_demo_batch,
    run_enterprise_support_demo,
)
from eval_pipeline.mlcommons_aix import (
    DEFAULT_MLCOMMONS_OUTPUT_DIR,
    DEFAULT_MLCOMMONS_PROFILE_PATH,
    DEFAULT_MLCOMMONS_RESULTS_PATH,
    MLCOMMONS_AIX_VERSION,
    build_mlcommons_aix_report,
    default_mlcommons_aix_profile,
    load_mlcommons_aix_profile,
    normalize_mlcommons_results,
    render_mlcommons_aix_report_markdown,
    run_mlcommons_aix_report,
    validate_mlcommons_aix_profile,
    validate_mlcommons_aix_report,
    write_mlcommons_aix_profile,
)
from eval_pipeline.mlcommons_endpoint_sidecar import (
    DEFAULT_MLCOMMONS_ENDPOINT_SIDECAR_CONTRACT_PATH,
    DEFAULT_MLCOMMONS_ENDPOINT_SIDECAR_REPORT_PATH,
    FAIL_CLOSED_REQUIRED_RULE as MLCOMMONS_ENDPOINT_FAIL_CLOSED_REQUIRED_RULE,
    MLCOMMONS_ENDPOINT_SIDECAR_CONTRACT_TYPE,
    MLCOMMONS_ENDPOINT_SIDECAR_VERSION,
    benchmark_run_metadata,
    default_endpoint_sidecar_contract,
    endpoint_precheck_contract,
    load_endpoint_sidecar_contract,
    sidecar_impact_report,
    validate_endpoint_sidecar_contract,
    validate_sidecar_impact_report,
    write_endpoint_sidecar_contract,
    write_endpoint_sidecar_readiness_report,
)
from eval_pipeline.mlcflow_aana_step import (
    DEFAULT_MLCFLOW_AANA_MANIFEST_PATH,
    DEFAULT_MLCFLOW_AANA_OUTPUT_DIR,
    MLCFLOW_AANA_STEP_MANIFEST_TYPE,
    MLCFLOW_AANA_STEP_VERSION,
    build_mlcflow_step_manifest,
    run_mlcflow_aana_step,
    validate_mlcflow_step_manifest,
)
from eval_pipeline.croissant_evidence import (
    CROISSANT_EVIDENCE_IMPORT_VERSION,
    DEFAULT_CROISSANT_EVIDENCE_OUTPUT_PATH,
    DEFAULT_CROISSANT_IMPORT_REPORT_PATH,
    DEFAULT_CROISSANT_METADATA_PATH,
    croissant_metadata_summary,
    croissant_to_evidence_registry,
    croissant_to_evidence_source,
    import_croissant_evidence,
)
from eval_pipeline.dataperf_dynabench_audit import (
    DATAPERF_DYNABENCH_AUDIT_VERSION,
    DATAPERF_DYNABENCH_PROFILE_TYPE,
    DEFAULT_DATAPERF_DYNABENCH_BENCHMARK_PATH,
    DEFAULT_DATAPERF_DYNABENCH_PROFILE_PATH,
    DEFAULT_DATAPERF_DYNABENCH_REPORT_PATH,
    benchmark_coverage_summary,
    dataset_quality_audit,
    default_dataperf_dynabench_profile,
    drift_risk_summary,
    risk_tier_recommendation,
    run_dataperf_dynabench_audit,
    validate_dataperf_dynabench_profile,
    write_dataperf_dynabench_profile,
)
from eval_pipeline.medperf_aix import (
    DEFAULT_MEDPERF_AIX_PROFILE_PATH,
    DEFAULT_MEDPERF_AIX_REPORT_PATH,
    MEDPERF_AIX_PROFILE_TYPE,
    MEDPERF_AIX_PROFILE_VERSION,
    MEDPERF_CLAIM_BOUNDARY,
    REQUIRED_HEALTHCARE_CONTEXT_FIELDS,
    build_medperf_aix_report_section,
    default_medperf_aix_profile,
    load_medperf_aix_profile,
    validate_medperf_aix_profile,
    write_medperf_aix_profile,
    write_medperf_aix_report_section,
)
from eval_pipeline.production_candidate_profile import (
    DEFAULT_PRODUCTION_CANDIDATE_PROFILE_PATH,
    PRODUCTION_CANDIDATE_PROFILE_TYPE,
    PRODUCTION_CANDIDATE_PROFILE_VERSION,
    default_production_candidate_profile,
    load_production_candidate_profile,
    validate_production_candidate_profile,
    write_production_candidate_profile,
)
from eval_pipeline.handoff_gate import HANDOFF_CONTRACT_VERSION, handoff_gate
from eval_pipeline.handoff_aix import HANDOFF_AIX_VERSION, calculate_handoff_aix
from eval_pipeline.workflow_aix import WORKFLOW_AIX_VERSION, calculate_global_aix, calculate_workflow_aix
from eval_pipeline.propagated_risk import PROPAGATED_RISK_VERSION, track_propagated_risk
from eval_pipeline.connectivity_risk import (
    CONNECTIVITY_RISK_VERSION,
    DEFAULT_RISK_TIER_RULES,
    assess_connectivity_risk,
    risk_tier_rules,
    tier_for_connectivity,
)
from eval_pipeline.shared_correction import (
    CORRECTION_ACTIONS,
    SHARED_CORRECTION_POLICY_VERSION,
    shared_correction_policy,
)
from eval_pipeline.correction_execution import (
    CORRECTION_EXECUTION_LOOP_VERSION,
    EXECUTABLE_CORRECTION_ROUTES,
    execute_correction_loop,
)
from eval_pipeline.mi_audit import (
    MI_AUDIT_RECORD_TYPE,
    MI_AUDIT_RECORD_VERSION,
    append_mi_audit_jsonl,
    load_mi_audit_jsonl,
    mi_audit_record,
    mi_audit_records,
    validate_mi_audit_record,
    validate_mi_audit_records,
)
from eval_pipeline.mi_audit_integrity import (
    DEFAULT_MI_AUDIT_MANIFEST_PATH,
    DEFAULT_MI_AUDIT_PATH,
    MI_AUDIT_INTEGRITY_MANIFEST_VERSION,
    load_mi_audit_integrity_manifest,
    mi_audit_integrity_manifest,
    validate_append_only_audit,
    validate_mi_audit_integrity_manifest,
    verify_mi_audit_integrity,
    write_mi_audit_integrity_manifest,
)
from eval_pipeline.immutable_audit_storage import (
    DEFAULT_IMMUTABLE_AUDIT_DIR,
    DEFAULT_IMMUTABLE_AUDIT_JSONL,
    DEFAULT_IMMUTABLE_AUDIT_MANIFEST,
    IMMUTABLE_AUDIT_STORAGE_VERSION,
    LocalImmutableAuditStorage,
    append_immutable_audit_records,
    immutable_audit_storage_contract,
    verify_immutable_audit_storage,
    write_immutable_audit_storage_contract,
)
from eval_pipeline.human_review_queue import (
    DEFAULT_HUMAN_REVIEW_QUEUE_PATH,
    HUMAN_DECISIONS,
    HUMAN_REVIEW_PACKET_TYPE,
    HUMAN_REVIEW_QUEUE_VERSION,
    append_human_review_queue_jsonl,
    enqueue_defer_reviews,
    human_review_packet,
    human_review_packets,
    load_human_review_queue_jsonl,
    validate_human_review_packet,
    validate_human_review_packets,
)
from eval_pipeline.runtime_human_review import (
    DEFAULT_RUNTIME_HUMAN_REVIEW_CONFIG_PATH,
    DEFAULT_RUNTIME_HUMAN_REVIEW_QUEUE_PATH,
    DEFAULT_RUNTIME_HUMAN_REVIEW_SUMMARY_PATH,
    RUNTIME_HUMAN_REVIEW_EXPORT_TYPE,
    RUNTIME_HUMAN_REVIEW_PACKET_TYPE,
    RUNTIME_HUMAN_REVIEW_VERSION,
    export_runtime_human_review_queue,
    human_review_export_config,
    load_runtime_human_review_queue,
    runtime_human_review_packet,
    runtime_human_review_packets,
    should_export_human_review_record,
    validate_human_review_export_config,
    validate_runtime_human_review_packet,
    validate_runtime_human_review_packets,
    write_human_review_export_config,
)
from eval_pipeline.live_monitoring import (
    DEFAULT_LIVE_MONITORING_CONFIG_PATH,
    DEFAULT_LIVE_MONITORING_REPORT_PATH,
    LIVE_MONITORING_CONFIG_TYPE,
    LIVE_MONITORING_REPORT_TYPE,
    LIVE_MONITORING_VERSION,
    live_monitoring_config,
    live_monitoring_report,
    live_monitoring_report_jsonl,
    load_live_monitoring_config,
    validate_live_monitoring_config,
    write_live_monitoring_config,
)
from eval_pipeline.production_candidate_check import (
    PRODUCTION_CANDIDATE_CHECK_TYPE,
    PRODUCTION_CANDIDATE_CHECK_VERSION,
    production_candidate_check,
)
from eval_pipeline.human_signoff import (
    DEFAULT_HUMAN_SIGNOFF_PATH,
    DEFAULT_RELEASE_MANIFEST_PATH,
    DEFAULT_RELEASE_VERIFICATION_PATH,
    HUMAN_SIGNOFF_RECORD_TYPE,
    HUMAN_SIGNOFF_VERSION,
    SIGNOFF_DECISIONS,
    human_signoff_record,
    validate_human_signoff_record,
    write_human_signoff_record,
)
from eval_pipeline.live_connector_readiness import (
    DEFAULT_LIVE_CONNECTOR_READINESS_PLAN_PATH,
    DEFAULT_REQUIRED_CONTROLS,
    LIVE_CONNECTOR_READINESS_PLAN_TYPE,
    LIVE_CONNECTOR_READINESS_VERSION,
    default_live_connectors,
    live_connector_readiness_plan,
    validate_live_connector_readiness_plan,
    write_live_connector_readiness_plan,
)
from eval_pipeline.production_deployment_manifest import (
    DEFAULT_PRODUCTION_DEPLOYMENT_MANIFEST_PATH,
    PRODUCTION_DEPLOYMENT_MANIFEST_TYPE,
    PRODUCTION_DEPLOYMENT_MANIFEST_VERSION,
    production_deployment_manifest,
    validate_production_deployment_manifest,
    write_production_deployment_manifest,
)
from eval_pipeline.post_release_monitoring import (
    DEFAULT_POST_RELEASE_MONITORING_POLICY_PATH,
    POST_RELEASE_MONITORING_POLICY_TYPE,
    POST_RELEASE_MONITORING_POLICY_VERSION,
    REQUIRED_ALERT_IDS,
    post_release_monitoring_policy,
    validate_post_release_monitoring_policy,
    write_post_release_monitoring_policy,
)
from eval_pipeline.production_dry_run import (
    DEFAULT_PRODUCTION_DRY_RUN_REPORT_PATH,
    PRODUCTION_DRY_RUN_REPORT_TYPE,
    PRODUCTION_DRY_RUN_VERSION,
    run_production_dry_run,
)
from eval_pipeline.production_go_no_go import (
    DEFAULT_PRODUCTION_GO_NO_GO_REPORT_PATH,
    PRODUCTION_GO_NO_GO_REPORT_TYPE,
    PRODUCTION_GO_NO_GO_VERSION,
    production_go_no_go_report,
    validate_production_go_no_go_report,
    write_production_go_no_go_report,
)
from eval_pipeline.mi_boundary_gate import (
    MI_BOUNDARY_GATE_VERSION,
    SUPPORTED_BOUNDARIES,
    infer_boundary_type,
    mi_boundary_batch,
    mi_boundary_gate,
)
from eval_pipeline.mi_contract_registry import (
    ACTIVE_MI_CONTRACT_VERSION,
    CORE_REQUIRED_CONSTRAINT_LAYERS,
    CORE_REQUIRED_FIELDS,
    CORE_REQUIRED_VERIFIER_LAYERS,
    MI_CONTRACT_REGISTRY_VERSION,
    check_contract_version_compatibility,
    contract_shape_for_boundary,
    infer_registered_boundary_type,
    mi_contract_registry,
    supported_boundaries,
    validate_mi_contract_compatibility,
)
from eval_pipeline.mi_benchmark import (
    BENCHMARK_MODES,
    MI_BENCHMARK_VERSION,
    benchmark_workflows,
    run_mi_benchmark,
    write_mi_benchmark_report,
    write_mi_benchmark_workflows,
)
from eval_pipeline.mi_observability import (
    MI_OBSERVABILITY_DASHBOARD_VERSION,
    mi_dashboard_from_benchmark,
    mi_dashboard_from_benchmark_file,
    write_mi_dashboard,
    write_mi_dashboard_from_benchmark,
)
from eval_pipeline.mi_release_candidate import (
    DEFAULT_MI_BENCHMARK_DIR,
    DEFAULT_MI_RELEASE_CANDIDATE_REPORT,
    MI_RELEASE_CANDIDATE_VERSION,
    run_mi_release_candidate,
)
from eval_pipeline.mi_release_bundle import (
    DEFAULT_ARTIFACTS,
    DEFAULT_MI_RELEASE_BUNDLE_DIR,
    MI_RELEASE_BUNDLE_VERSION,
    create_mi_release_bundle,
    release_note_markdown,
)
from eval_pipeline.mi_release_bundle_verification import (
    DEFAULT_RELEASE_BUNDLE_VERIFICATION_PATH,
    MI_RELEASE_BUNDLE_VERIFICATION_VERSION,
    verify_mi_release_bundle,
)
from eval_pipeline.mi_release import (
    DEFAULT_MI_RELEASE_REPORT,
    MI_RELEASE_COMMAND_VERSION,
    run_mi_release,
)
from eval_pipeline.mi_pilot import (
    MI_PILOT_VERSION,
    research_citation_pilot_handoffs,
    run_research_citation_mi_pilot,
    write_research_citation_mi_pilot,
)
from eval_pipeline.pilot_hardening import (
    GUARDED_LIVE_PILOT_ID,
    PILOT_HARDENING_VERSION,
    guarded_pilot_execution_decision,
    guarded_pilot_rollback_plan,
    run_guarded_research_citation_pilot,
    write_guarded_research_citation_pilot,
)
from eval_pipeline.production_readiness import (
    PRODUCTION_MI_READINESS_VERSION,
    production_mi_readiness_gate,
    production_mi_release_checklist_markdown,
    write_production_mi_readiness_result,
    write_production_mi_release_checklist,
)
from eval_pipeline.release_adapter_integration import (
    RELEASE_ADAPTER_INTEGRATION_VERSION,
    attach_deployment_release_readiness,
    deployment_release_mi_batch,
    is_deployment_release_adapter,
)
from eval_pipeline.release_blocker_remediation import (
    RELEASE_BLOCKER_REMEDIATION_VERSION,
    corrected_research_citation_handoffs,
    run_research_citation_remediation,
    write_research_citation_remediation,
)
from eval_pipeline.release_readiness_report import (
    DEFAULT_RELEASE_ARTIFACT_PATHS,
    DEFAULT_RELEASE_REPORT_PATH,
    RELEASE_READINESS_REPORT_VERSION,
    parse_release_checklist_markdown,
    release_readiness_report,
    write_release_readiness_report,
)
from eval_pipeline.pre_execution_hook import (
    PRE_EXECUTION_DECISIONS,
    PRE_EXECUTION_HOOK_VERSION,
    pre_execution_hook,
)
from eval_pipeline.privacy_review import (
    MI_PRIVACY_REVIEW_VERSION,
    RAW_PRIVATE_FIELD_NAMES,
    SECRET_PATTERNS,
    privacy_issues,
    validate_redacted_artifact,
    validate_redacted_artifacts,
)
from eval_pipeline.schema_versioning_policy import (
    ACTIVE_INTEROPERABILITY_SCHEMA_VERSION,
    BREAKING_CHANGE_RULES,
    COMPATIBILITY_MATRIX,
    DEFAULT_SCHEMA_VERSIONING_POLICY_JSON_PATH,
    DEFAULT_SCHEMA_VERSIONING_POLICY_PATH,
    MIGRATION_NOTES,
    SCHEMA_VERSIONING_POLICY_VERSION,
    check_schema_artifact_compatibility,
    schema_versioning_policy,
    schema_versioning_policy_markdown,
    write_schema_versioning_policy,
    write_schema_versioning_policy_json,
)
from eval_pipeline.evidence_integrations import (
    CIVIC_CONNECTOR_CONTRACT_IDS,
    CORE_CONNECTOR_CONTRACT_IDS,
    EvidenceAuthContext,
    EvidenceConnectorFailure,
    EvidenceConnectorResult,
    EvidenceFetchRequest,
    LiveEvidenceConnectorManifest,
    LiveHTTPJSONEvidenceConnector,
    SUPPORT_CONNECTOR_CONTRACT_IDS,
    build_live_support_connectors,
    live_support_connector_manifests,
    run_live_support_connector,
)
from eval_pipeline.evidence import (
    DEFAULT_EVIDENCE_REGISTRY_PATH,
    EVIDENCE_OBJECT_VERSION,
    EvidenceObject,
    default_evidence_registry,
    evidence_source_contract,
    validate_evidence_registry_binding,
    validate_evidence_object,
    validate_evidence_objects,
    validate_handoff_evidence_binding,
)
from eval_pipeline.runtime import (
    RUNTIME_API_VERSION,
    AANACheckError,
    AANAError,
    AANAInputError,
    AANAValidationError,
    RuntimeResult,
    ValidationReport,
    check as check_typed,
    check_batch as check_batch_typed,
    check_batch_file as check_batch_file_typed,
    check_file as check_file_typed,
    check_request as check_request_typed,
    load_json_object,
    schemas as runtime_schemas,
    validate_batch as validate_batch_typed,
    validate_request as validate_request_typed,
)
from eval_pipeline.workflow_contract import WorkflowBatchRequest, WorkflowBatchResult, WorkflowRequest, WorkflowResult
from aana.sdk import (
    AANAClient,
    AANAClientError,
    CivicAANAClient,
    EnterpriseAANAClient,
    EnterpriseOpsPilotAANAClient,
    FamilyAANAClient,
    PersonalAANAClient,
    ROUTE_TABLE,
    SupportAANAClient,
    TOOL_PRECHECK_SCHEMA_VERSION,
    PUBLIC_ARCHITECTURE_CLAIM,
    analyze_tool_evidence_refs,
    architecture_decision,
    audit_safe_decision_event,
    build_agent_event,
    build_family_workflow_request,
    build_tool_precheck_event,
    build_workflow_request,
    check_tool_call,
    check_tool_precheck,
    check_tool_precheck_v2,
    client,
    evidence_object,
    execution_policy,
    gate_action,
    grounded_qa_evidence_coverage,
    normalize_evidence,
    normalize_tool_call_event,
    normalize_tool_evidence_refs,
    route_allows_execution,
    should_execute_tool,
    tool_evidence_ref,
    validate_tool_precheck_event,
    with_architecture_decision,
)
from aana.middleware import (
    AANAToolExecutionBlocked,
    autogen_tool_middleware,
    build_precheck_from_tool_call,
    crewai_tool_middleware,
    execute_tool_if_allowed,
    gate_tool_call,
    guard_tool_function,
    infer_risk_domain,
    infer_tool_category,
    langchain_tool_middleware,
    middleware_error,
    mcp_tool_middleware,
    openai_agents_tool_middleware,
    wrap_agent_tool,
)
from aana.registry import load_registry as load_platform_registry, registry as platform_registry
from eval_pipeline.semantic_verifier import OpenAISemanticVerifier, build_semantic_verifier


__version__ = "0.1.0"


def check(
    adapter,
    request,
    candidate=None,
    evidence=None,
    constraints=None,
    allowed_actions=None,
    metadata=None,
    workflow_id=None,
    gallery_path=None,
):
    """Check a proposed AI output or action against an AANA workflow adapter.

    Returns a dictionary with gate_decision, recommended_action, violations,
    output, and the raw underlying adapter result.
    """

    kwargs = {
        "adapter": adapter,
        "request": request,
        "candidate": candidate,
        "evidence": evidence,
        "constraints": constraints,
        "allowed_actions": allowed_actions,
        "metadata": metadata,
        "workflow_id": workflow_id,
    }
    if gallery_path is not None:
        kwargs["gallery_path"] = gallery_path
    return check_workflow(**kwargs)


def check_request(workflow_request, gallery_path=None):
    """Check a Workflow Contract request dictionary or WorkflowRequest object."""

    if isinstance(workflow_request, WorkflowRequest):
        workflow_request = workflow_request.to_dict()
    if gallery_path is not None:
        return check_workflow_request(workflow_request, gallery_path=gallery_path)
    return check_workflow_request(workflow_request)


def check_batch(batch_request, gallery_path=None):
    """Check a Workflow Batch Contract dictionary or WorkflowBatchRequest object."""

    if isinstance(batch_request, WorkflowBatchRequest):
        batch_request = batch_request.to_dict()
    if gallery_path is not None:
        return check_workflow_batch(batch_request, gallery_path=gallery_path)
    return check_workflow_batch(batch_request)


def check_file(path, gallery_path=None):
    """Load a Workflow Contract JSON file and run the AANA gate."""

    with pathlib.Path(path).open(encoding="utf-8") as handle:
        workflow_request = json.load(handle)
    return check_request(workflow_request, gallery_path=gallery_path)


def check_batch_file(path, gallery_path=None):
    """Load a Workflow Batch Contract JSON file and run all AANA gates."""

    with pathlib.Path(path).open(encoding="utf-8") as handle:
        batch_request = json.load(handle)
    return check_batch(batch_request, gallery_path=gallery_path)


def result_object(result):
    """Convert a workflow result dictionary into a small typed object."""

    return WorkflowResult.from_dict(result)


def batch_result_object(result):
    """Convert a workflow batch result dictionary into a small typed object."""

    return WorkflowBatchResult.from_dict(result)


__all__ = [
    "WORKFLOW_CONTRACT_VERSION",
    "HANDOFF_CONTRACT_VERSION",
    "HANDOFF_AIX_VERSION",
    "WORKFLOW_AIX_VERSION",
    "PROPAGATED_RISK_VERSION",
    "CONNECTIVITY_RISK_VERSION",
    "SHARED_CORRECTION_POLICY_VERSION",
    "CORRECTION_EXECUTION_LOOP_VERSION",
    "MI_AUDIT_RECORD_VERSION",
    "MI_AUDIT_RECORD_TYPE",
    "MI_AUDIT_INTEGRITY_MANIFEST_VERSION",
    "IMMUTABLE_AUDIT_STORAGE_VERSION",
    "DURABLE_AUDIT_STORAGE_VERSION",
    "DURABLE_AUDIT_STORAGE_TYPE",
    "HUMAN_REVIEW_QUEUE_VERSION",
    "HUMAN_REVIEW_PACKET_TYPE",
    "HUMAN_SIGNOFF_VERSION",
    "HUMAN_SIGNOFF_RECORD_TYPE",
    "LIVE_CONNECTOR_READINESS_VERSION",
    "LIVE_CONNECTOR_READINESS_PLAN_TYPE",
    "PRODUCTION_DEPLOYMENT_MANIFEST_VERSION",
    "PRODUCTION_DEPLOYMENT_MANIFEST_TYPE",
    "POST_RELEASE_MONITORING_POLICY_VERSION",
    "POST_RELEASE_MONITORING_POLICY_TYPE",
    "PRODUCTION_DRY_RUN_VERSION",
    "PRODUCTION_DRY_RUN_REPORT_TYPE",
    "PRODUCTION_GO_NO_GO_VERSION",
    "PRODUCTION_GO_NO_GO_REPORT_TYPE",
    "MI_BENCHMARK_VERSION",
    "MI_OBSERVABILITY_DASHBOARD_VERSION",
    "MI_RELEASE_CANDIDATE_VERSION",
    "MI_RELEASE_BUNDLE_VERSION",
    "MI_RELEASE_BUNDLE_VERIFICATION_VERSION",
    "MI_RELEASE_COMMAND_VERSION",
    "MI_PILOT_VERSION",
    "PILOT_HARDENING_VERSION",
    "PRODUCTION_MI_READINESS_VERSION",
    "RELEASE_ADAPTER_INTEGRATION_VERSION",
    "RELEASE_BLOCKER_REMEDIATION_VERSION",
    "RELEASE_READINESS_REPORT_VERSION",
    "PRE_EXECUTION_HOOK_VERSION",
    "MI_PRIVACY_REVIEW_VERSION",
    "SCHEMA_VERSIONING_POLICY_VERSION",
    "ACTIVE_INTEROPERABILITY_SCHEMA_VERSION",
    "BENCHMARK_MODES",
    "DEFAULT_RISK_TIER_RULES",
    "CORRECTION_ACTIONS",
    "EXECUTABLE_CORRECTION_ROUTES",
    "EVIDENCE_OBJECT_VERSION",
    "DEFAULT_EVIDENCE_REGISTRY_PATH",
    "MI_BOUNDARY_GATE_VERSION",
    "MI_CONTRACT_REGISTRY_VERSION",
    "ACTIVE_MI_CONTRACT_VERSION",
    "GUARDED_LIVE_PILOT_ID",
    "SUPPORTED_BOUNDARIES",
    "PRE_EXECUTION_DECISIONS",
    "RAW_PRIVATE_FIELD_NAMES",
    "SECRET_PATTERNS",
    "HUMAN_DECISIONS",
    "SIGNOFF_DECISIONS",
    "DEFAULT_REQUIRED_CONTROLS",
    "REQUIRED_ALERT_IDS",
    "REQUIRED_HEALTHCARE_CONTEXT_FIELDS",
    "DEFAULT_HUMAN_REVIEW_QUEUE_PATH",
    "DEFAULT_HUMAN_SIGNOFF_PATH",
    "DEFAULT_LIVE_CONNECTOR_READINESS_PLAN_PATH",
    "DEFAULT_PRODUCTION_DEPLOYMENT_MANIFEST_PATH",
    "DEFAULT_POST_RELEASE_MONITORING_POLICY_PATH",
    "DEFAULT_PRODUCTION_DRY_RUN_REPORT_PATH",
    "DEFAULT_PRODUCTION_GO_NO_GO_REPORT_PATH",
    "DEFAULT_RELEASE_MANIFEST_PATH",
    "DEFAULT_RELEASE_VERIFICATION_PATH",
    "DEFAULT_MI_AUDIT_PATH",
    "DEFAULT_MI_AUDIT_MANIFEST_PATH",
    "DEFAULT_IMMUTABLE_AUDIT_DIR",
    "DEFAULT_IMMUTABLE_AUDIT_JSONL",
    "DEFAULT_IMMUTABLE_AUDIT_MANIFEST",
    "DEFAULT_DURABLE_AUDIT_CONFIG_PATH",
    "DEFAULT_DURABLE_AUDIT_DIR",
    "DEFAULT_DURABLE_AUDIT_JSONL",
    "DEFAULT_DURABLE_AUDIT_MANIFEST",
    "DEFAULT_RELEASE_ARTIFACT_PATHS",
    "DEFAULT_RELEASE_REPORT_PATH",
    "DEFAULT_MI_BENCHMARK_DIR",
    "DEFAULT_MI_RELEASE_CANDIDATE_REPORT",
    "DEFAULT_ARTIFACTS",
    "DEFAULT_MI_RELEASE_BUNDLE_DIR",
    "DEFAULT_RELEASE_BUNDLE_VERIFICATION_PATH",
    "DEFAULT_MI_RELEASE_REPORT",
    "BREAKING_CHANGE_RULES",
    "COMPATIBILITY_MATRIX",
    "DEFAULT_SCHEMA_VERSIONING_POLICY_JSON_PATH",
    "DEFAULT_SCHEMA_VERSIONING_POLICY_PATH",
    "MIGRATION_NOTES",
    "CORE_REQUIRED_FIELDS",
    "CORE_REQUIRED_CONSTRAINT_LAYERS",
    "CORE_REQUIRED_VERIFIER_LAYERS",
    "RUNTIME_API_VERSION",
    "AANACheckError",
    "AANAError",
    "AANAInputError",
    "AANAValidationError",
    "AANAClient",
    "AANAClientError",
    "AANAToolExecutionBlocked",
    "CivicAANAClient",
    "CIVIC_CONNECTOR_CONTRACT_IDS",
    "CORE_CONNECTOR_CONTRACT_IDS",
    "SUPPORT_CONNECTOR_CONTRACT_IDS",
    "EnterpriseAANAClient",
    "EnterpriseOpsPilotAANAClient",
    "EvidenceAuthContext",
    "EvidenceConnectorFailure",
    "EvidenceConnectorResult",
    "EvidenceFetchRequest",
    "EvidenceObject",
    "LocalImmutableAuditStorage",
    "LocalDurableAuditStorage",
    "LiveEvidenceConnectorManifest",
    "LiveHTTPJSONEvidenceConnector",
    "FamilyAANAClient",
    "PersonalAANAClient",
    "SupportAANAClient",
    "TOOL_PRECHECK_SCHEMA_VERSION",
    "PUBLIC_ARCHITECTURE_CLAIM",
    "RuntimeResult",
    "ValidationReport",
    "WorkflowBatchRequest",
    "WorkflowBatchResult",
    "WorkflowRequest",
    "WorkflowResult",
    "append_audit_record",
    "apply_shadow_mode",
    "audit_aix_drift_report",
    "audit_aix_drift_report_file",
    "audit_dashboard",
    "audit_dashboard_file",
    "audit_event_check",
    "audit_redaction_report",
    "audit_workflow_batch",
    "audit_workflow_check",
    "autogen_tool_middleware",
    "check",
    "check_batch",
    "check_batch_file",
    "check_file",
    "check_request",
    "handoff_gate",
    "infer_risk_domain",
    "infer_tool_category",
    "infer_boundary_type",
    "infer_registered_boundary_type",
    "mi_boundary_batch",
    "mi_boundary_gate",
    "mi_contract_registry",
    "mcp_tool_middleware",
    "supported_boundaries",
    "contract_shape_for_boundary",
    "check_contract_version_compatibility",
    "validate_mi_contract_compatibility",
    "check_typed",
    "check_batch_typed",
    "check_batch_file_typed",
    "check_file_typed",
    "check_request_typed",
    "check_workflow",
    "check_workflow_batch",
    "check_workflow_request",
    "evidence_connector_contracts",
    "evidence_connector_marketplace",
    "evidence_integration_coverage",
    "evidence_integration_stubs",
    "evidence_mock_connector_matrix",
    "export_audit_metrics",
    "export_audit_metrics_file",
    "load_audit_records",
    "load_evidence_mock_fixtures",
    "load_evidence_registry",
    "load_json_object",
    "langchain_tool_middleware",
    "middleware_error",
    "normalize_evidence_object",
    "run_evidence_mock_connector",
    "build_live_support_connectors",
    "live_support_connector_manifests",
    "run_live_support_connector",
    "support_evidence_boundary",
    "batch_result_object",
    "build_agent_event",
    "build_family_workflow_request",
    "build_precheck_from_tool_call",
    "build_tool_precheck_event",
    "build_workflow_request",
    "architecture_decision",
    "audit_safe_decision_event",
    "check_tool_call",
    "check_tool_precheck",
    "check_tool_precheck_v2",
    "OpenAISemanticVerifier",
    "build_semantic_verifier",
    "calculate_aix",
    "AIX_REPORT_SCHEMA",
    "DEFAULT_ENTERPRISE_CONNECTOR_READINESS_PATH",
    "DEFAULT_ENTERPRISE_LIVE_CONNECTORS_PATH",
    "DEFAULT_PRODUCTION_CANDIDATE_PROFILE_PATH",
    "ENTERPRISE_CONNECTOR_READINESS_TYPE",
    "ENTERPRISE_CONNECTOR_READINESS_VERSION",
    "ENTERPRISE_CONNECTOR_EXECUTION_MODES",
    "ENTERPRISE_LIVE_CONNECTORS_TYPE",
    "ENTERPRISE_LIVE_CONNECTORS_VERSION",
    "ENTERPRISE_SUPPORT_DEMO_VERSION",
    "MLCOMMONS_AIX_VERSION",
    "MLCOMMONS_ENDPOINT_SIDECAR_VERSION",
    "MLCFLOW_AANA_STEP_VERSION",
    "CROISSANT_EVIDENCE_IMPORT_VERSION",
    "DATAPERF_DYNABENCH_AUDIT_VERSION",
    "MEDPERF_AIX_PROFILE_VERSION",
    "DEFAULT_CROISSANT_EVIDENCE_OUTPUT_PATH",
    "DEFAULT_CROISSANT_IMPORT_REPORT_PATH",
    "DEFAULT_CROISSANT_METADATA_PATH",
    "DEFAULT_DATAPERF_DYNABENCH_BENCHMARK_PATH",
    "DEFAULT_DATAPERF_DYNABENCH_PROFILE_PATH",
    "DEFAULT_DATAPERF_DYNABENCH_REPORT_PATH",
    "DEFAULT_MEDPERF_AIX_PROFILE_PATH",
    "DEFAULT_MEDPERF_AIX_REPORT_PATH",
    "DEFAULT_MLCOMMONS_OUTPUT_DIR",
    "DEFAULT_MLCOMMONS_PROFILE_PATH",
    "DEFAULT_MLCOMMONS_RESULTS_PATH",
    "DEFAULT_MLCOMMONS_ENDPOINT_SIDECAR_CONTRACT_PATH",
    "DEFAULT_MLCOMMONS_ENDPOINT_SIDECAR_REPORT_PATH",
    "DEFAULT_MLCFLOW_AANA_MANIFEST_PATH",
    "DEFAULT_MLCFLOW_AANA_OUTPUT_DIR",
    "PRODUCTION_CANDIDATE_PROFILE_TYPE",
    "PRODUCTION_CANDIDATE_PROFILE_VERSION",
    "MLCOMMONS_ENDPOINT_SIDECAR_CONTRACT_TYPE",
    "MLCOMMONS_ENDPOINT_FAIL_CLOSED_REQUIRED_RULE",
    "MLCFLOW_AANA_STEP_MANIFEST_TYPE",
    "MEDPERF_AIX_PROFILE_TYPE",
    "DATAPERF_DYNABENCH_PROFILE_TYPE",
    "REQUIRED_CONNECTOR_IDS",
    "SUPPORT_ACTION_CONNECTOR_IDS",
    "EnterpriseConnectorError",
    "EnterpriseConnectorManifest",
    "EnterpriseHTTPJSONConnector",
    "aana_allows_execution",
    "build_aix_report",
    "build_enterprise_dashboard",
    "build_enterprise_support_demo_batch",
    "build_mlcommons_aix_report",
    "benchmark_run_metadata",
    "build_mlcflow_step_manifest",
    "build_medperf_aix_report_section",
    "croissant_metadata_summary",
    "croissant_to_evidence_registry",
    "croissant_to_evidence_source",
    "benchmark_coverage_summary",
    "dataset_quality_audit",
    "build_enterprise_support_connectors",
    "default_enterprise_connectors",
    "default_enterprise_live_connector_config",
    "default_production_candidate_profile",
    "default_mlcommons_aix_profile",
    "default_endpoint_sidecar_contract",
    "default_medperf_aix_profile",
    "default_dataperf_dynabench_profile",
    "enterprise_connector_readiness_plan",
    "enterprise_connector_manifests",
    "load_enterprise_live_connector_config",
    "load_production_candidate_profile",
    "load_mlcommons_aix_profile",
    "load_endpoint_sidecar_contract",
    "load_medperf_aix_profile",
    "drift_risk_summary",
    "load_enterprise_adapter_config",
    "load_enterprise_calibration_fixtures",
    "materialize_enterprise_ops_batch",
    "render_aix_report_markdown",
    "render_mlcommons_aix_report_markdown",
    "endpoint_precheck_contract",
    "run_enterprise_ops_aix_audit",
    "run_enterprise_support_connector_smoke",
    "run_enterprise_support_demo",
    "run_mlcommons_aix_report",
    "run_dataperf_dynabench_audit",
    "run_mlcflow_aana_step",
    "sidecar_impact_report",
    "import_croissant_evidence",
    "MEDPERF_CLAIM_BOUNDARY",
    "normalize_mlcommons_results",
    "validate_enterprise_adapter_config",
    "validate_enterprise_calibration_fixtures",
    "validate_aix_report",
    "validate_enterprise_connector_readiness_plan",
    "validate_enterprise_live_connector_config",
    "validate_production_candidate_profile",
    "validate_mlcommons_aix_profile",
    "validate_mlcommons_aix_report",
    "validate_endpoint_sidecar_contract",
    "validate_sidecar_impact_report",
    "validate_mlcflow_step_manifest",
    "validate_medperf_aix_profile",
    "validate_dataperf_dynabench_profile",
    "write_enterprise_connector_readiness_plan",
    "write_enterprise_live_connector_config",
    "write_production_candidate_profile",
    "write_mlcommons_aix_profile",
    "write_endpoint_sidecar_contract",
    "write_endpoint_sidecar_readiness_report",
    "write_medperf_aix_profile",
    "write_medperf_aix_report_section",
    "write_dataperf_dynabench_profile",
    "risk_tier_recommendation",
    "calculate_handoff_aix",
    "calculate_global_aix",
    "calculate_workflow_aix",
    "track_propagated_risk",
    "assess_connectivity_risk",
    "risk_tier_rules",
    "tier_for_connectivity",
    "shared_correction_policy",
    "execute_correction_loop",
    "execute_tool_if_allowed",
    "gate_tool_call",
    "gate_action",
    "guard_tool_function",
    "mi_audit_record",
    "mi_audit_records",
    "append_mi_audit_jsonl",
    "load_mi_audit_jsonl",
    "validate_mi_audit_record",
    "validate_mi_audit_records",
    "mi_audit_integrity_manifest",
    "write_mi_audit_integrity_manifest",
    "load_mi_audit_integrity_manifest",
    "validate_mi_audit_integrity_manifest",
    "verify_mi_audit_integrity",
    "validate_append_only_audit",
    "append_immutable_audit_records",
    "append_durable_audit_records",
    "durable_audit_storage_config",
    "import_audit_log_to_durable_storage",
    "immutable_audit_storage_contract",
    "validate_durable_audit_storage_config",
    "verify_durable_audit_storage",
    "verify_immutable_audit_storage",
    "write_durable_audit_storage_config",
    "write_immutable_audit_storage_contract",
    "human_review_packet",
    "human_review_packets",
    "append_human_review_queue_jsonl",
    "load_human_review_queue_jsonl",
    "validate_human_review_packet",
    "validate_human_review_packets",
    "enqueue_defer_reviews",
    "runtime_human_review_packet",
    "runtime_human_review_packets",
    "export_runtime_human_review_queue",
    "human_review_export_config",
    "load_runtime_human_review_queue",
    "should_export_human_review_record",
    "validate_human_review_export_config",
    "validate_runtime_human_review_packet",
    "validate_runtime_human_review_packets",
    "write_human_review_export_config",
    "DEFAULT_RUNTIME_HUMAN_REVIEW_CONFIG_PATH",
    "DEFAULT_RUNTIME_HUMAN_REVIEW_QUEUE_PATH",
    "DEFAULT_RUNTIME_HUMAN_REVIEW_SUMMARY_PATH",
    "RUNTIME_HUMAN_REVIEW_EXPORT_TYPE",
    "RUNTIME_HUMAN_REVIEW_PACKET_TYPE",
    "RUNTIME_HUMAN_REVIEW_VERSION",
    "live_monitoring_config",
    "live_monitoring_report",
    "live_monitoring_report_jsonl",
    "load_live_monitoring_config",
    "validate_live_monitoring_config",
    "write_live_monitoring_config",
    "DEFAULT_LIVE_MONITORING_CONFIG_PATH",
    "DEFAULT_LIVE_MONITORING_REPORT_PATH",
    "LIVE_MONITORING_CONFIG_TYPE",
    "LIVE_MONITORING_REPORT_TYPE",
    "LIVE_MONITORING_VERSION",
    "production_candidate_check",
    "PRODUCTION_CANDIDATE_CHECK_TYPE",
    "PRODUCTION_CANDIDATE_CHECK_VERSION",
    "human_signoff_record",
    "validate_human_signoff_record",
    "write_human_signoff_record",
    "default_live_connectors",
    "live_connector_readiness_plan",
    "validate_live_connector_readiness_plan",
    "write_live_connector_readiness_plan",
    "production_deployment_manifest",
    "validate_production_deployment_manifest",
    "write_production_deployment_manifest",
    "post_release_monitoring_policy",
    "validate_post_release_monitoring_policy",
    "write_post_release_monitoring_policy",
    "run_production_dry_run",
    "production_go_no_go_report",
    "validate_production_go_no_go_report",
    "write_production_go_no_go_report",
    "benchmark_workflows",
    "run_mi_benchmark",
    "write_mi_benchmark_report",
    "write_mi_benchmark_workflows",
    "mi_dashboard_from_benchmark",
    "mi_dashboard_from_benchmark_file",
    "write_mi_dashboard",
    "write_mi_dashboard_from_benchmark",
    "run_mi_release_candidate",
    "create_mi_release_bundle",
    "release_note_markdown",
    "verify_mi_release_bundle",
    "run_mi_release",
    "research_citation_pilot_handoffs",
    "run_research_citation_mi_pilot",
    "write_research_citation_mi_pilot",
    "guarded_pilot_execution_decision",
    "guarded_pilot_rollback_plan",
    "run_guarded_research_citation_pilot",
    "write_guarded_research_citation_pilot",
    "production_mi_readiness_gate",
    "production_mi_release_checklist_markdown",
    "write_production_mi_readiness_result",
    "write_production_mi_release_checklist",
    "attach_deployment_release_readiness",
    "deployment_release_mi_batch",
    "is_deployment_release_adapter",
    "corrected_research_citation_handoffs",
    "run_research_citation_remediation",
    "write_research_citation_remediation",
    "parse_release_checklist_markdown",
    "release_readiness_report",
    "write_release_readiness_report",
    "pre_execution_hook",
    "privacy_issues",
    "validate_redacted_artifact",
    "validate_redacted_artifacts",
    "schema_versioning_policy",
    "schema_versioning_policy_markdown",
    "check_schema_artifact_compatibility",
    "write_schema_versioning_policy",
    "write_schema_versioning_policy_json",
    "client",
    "crewai_tool_middleware",
    "decision_from_score",
    "result_object",
    "runtime_schemas",
    "ROUTE_TABLE",
    "load_platform_registry",
    "platform_registry",
    "schema_catalog",
    "normalize_evidence",
    "normalize_tool_call_event",
    "normalize_tool_evidence_refs",
    "route_allows_execution",
    "openai_agents_tool_middleware",
    "wrap_agent_tool",
    "execution_policy",
    "analyze_tool_evidence_refs",
    "grounded_qa_evidence_coverage",
    "should_execute_tool",
    "tool_evidence_ref",
    "validate_tool_precheck_event",
    "with_architecture_decision",
    "evidence_object",
    "validate_evidence_object",
    "validate_evidence_objects",
    "default_evidence_registry",
    "evidence_source_contract",
    "validate_evidence_registry_binding",
    "validate_handoff_evidence_binding",
    "summarize_audit_file",
    "summarize_audit_records",
    "validate_batch_typed",
    "validate_audit_file",
    "validate_audit_metrics_export",
    "validate_audit_records",
    "validate_workflow_batch_evidence",
    "validate_evidence_registry",
    "validate_request_typed",
    "validate_workflow_evidence",
    "validate_workflow_batch_request",
    "validate_workflow_request",
    "write_audit_reviewer_report",
]
